name: boozin_fitness
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6

  get: 4.6.6
  health: 9.0.1
  flutter_svg: 2.0.10+1
  intl: 0.19.0
  get_storage: 2.1.1
  lottie: ^3.1.0
  flutter_native_splash: ^2.3.13
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
