on:
  pull_request:
    branches: [master]
  push:
    branches: master
name: "Build & release"
jobs:
  build:
    name: Build & release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.3"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter pub run flutter_native_splash:create
      - run: flutter build apk --release

      - name: Push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: v1.0.${{github.run_number}}
          token: ${{ secrets.TOKEN }}
